"""add dashboard metrics and request logs

Revision ID: f24d41363800
Revises: 
Create Date: 2026-07-28 08:41:02.395049+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f24d41363800'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tunnel_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tunnel_id'], ['tunnel_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_created_at'), 'request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_tunnel_id'), 'request_logs', ['tunnel_id'], unique=False)
    op.add_column('tunnel_records', sa.Column('protocol', sa.String(length=16), nullable=False))
    op.add_column('tunnel_records', sa.Column('target', sa.String(length=255), nullable=True))
    op.add_column('tunnel_records', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('tunnel_records', sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tunnel_records', sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tunnel_records', sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tunnel_records', sa.Column('bytes_uploaded', sa.Integer(), nullable=False))
    op.add_column('tunnel_records', sa.Column('bytes_downloaded', sa.Integer(), nullable=False))
    op.add_column('tunnel_records', sa.Column('request_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tunnel_records', 'request_count')
    op.drop_column('tunnel_records', 'bytes_downloaded')
    op.drop_column('tunnel_records', 'bytes_uploaded')
    op.drop_column('tunnel_records', 'last_heartbeat')
    op.drop_column('tunnel_records', 'disconnected_at')
    op.drop_column('tunnel_records', 'connected_at')
    op.drop_column('tunnel_records', 'started_at')
    op.drop_column('tunnel_records', 'target')
    op.drop_column('tunnel_records', 'protocol')
    op.drop_index(op.f('ix_request_logs_tunnel_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_created_at'), table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
