apiVersion: v1
kind: Service
metadata:
  name: hushh-server
  namespace: hushh
  labels:
    app: hushh-server
    app.kubernetes.io/name: hushh-tunnel
spec:
  type: ClusterIP
  selector:
    app: hushh-server
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
